export const products = [
	{
		id: "1000",
		code: "f230fh0g3",
		name: "Bamboo Watch",
		location: "Product location",
		image: "https://cityquest.in/_next/image?url=https%3A%2F%2Fcityquest-production.s3.ap-south-1.amazonaws.com%2Fadmin-assets%2Fmaze.jpg&w=1920&q=75",
		price: 65,
		category: "Accessories",
		quantity: 24,
		inventoryStatus: "INSTOCK",
		rating: 5,
		iamge: 'https://i.redd.it/4l9holkqy8z01.jpg',
	},
	{
		id: "1001",
		code: "nvklal433",
		name: "Black Watch",
		location: "Product location",
		image: "https://cityquest.in/_next/image?url=https%3A%2F%2Fcityquest-production.s3.ap-south-1.amazonaws.com%2Fadmin-assets%2Fact.png&w=1920&q=75",
		price: 72,
		category: "Accessories",
		quantity: 61,
		inventoryStatus: "INSTOCK",
		rating: 4,
		//iamge: banner,
	},
	{
		id: "1002",
		code: "zz21cz3c1",
		name: "Blue Band",
		location: "Product location",
		image: "https://cityquest.in/_next/image?url=https%3A%2F%2Fcityquest-production.s3.ap-south-1.amazonaws.com%2Fadmin-assets%2Fvihe%2520james.png&w=1920&q=75",
		price: 79,
		category: "Fitness",
		quantity: 2,
		inventoryStatus: "LOWSTOCK",
		rating: 3,
	//	iamge: banner,
	}
	
];
