const eventImages = [
     {
        "id": 695,
        "title": "Fashionista Fashion Lifestyle Exhibition - 37th Edition",
        "status": "Published",
        "description": "<p>Royalty at its best. Fashionista is all set to introduce you all to the traditional glory of the royals alive. We are bringing bespoke bridal couture, glorious and exclusive ensembles, astounding jewelry, footwear accessories, and many more...</p><p>Coimbatore, be a part of this mega exhibition with a traditional yet chic and eclectic ensemble and set the mood for all the seasons.</p><p><br></p><p><strong>FREE ENTRY for VISITORS</strong></p>",
        "priority": false,
        "from": "2024-12-07T05:30:00.000Z",
        "to": "2024-12-08T15:30:00.000Z",
        "place": "Vivanta By Taj",
        "address": "Vivanta By Taj,\nRace Course Road,\nGopalapuram, \nCoimbatore.",
        "websites": "www.fashionistaindia.com",
        "email": null,
        "contacts": [
            "8585857816"
        ],
        "date": "12 Oct, 2024",
        "time": "7 - 10 PM",
        "area_1": "Race Course",
        "area_2": null,
        "area_3": null,
        "city": "Coimbatore",
        "state": null,
        "country": null,
        "zipcode": "641018",
        "priorities": null,
        "is_favourite": null,
        "on_reminder": null,
        "favourite_count": "0",
        "location": {
            "latitude": null,
            "longitude": null
        },
        "category": "LifeStyle Exhibition",
        "poster": "https://cityquest-production.s3.ap-south-1.amazonaws.com/admin-assets/fashionista.png"
    },
    {
        "id": 675,
        "title": "50 Years of Rajinism",
        "status": "Published",
        "description": "<p>Get ready to witness the Mega musical Journey from 1975 to 2024 and on. Songs From Apoorva Raagangal to Vettaiyan to mark our Thailavar one and only Rajinikanth`s 50 Years of charismatic stardom. Man of Masses. epitome of Style, greatest human being and many more. First time in Coimbatore mega music mania of Thailavar Hits. Most popular Musical band Mouna Raagam Murali with professional singers and top class Orchestra. Mimicry by Erode Sanjay. Organised by 7 eleven Entertainment inc in association with Tom Mediaas, Sammy media works and DriveX.</p><p><br></p><p><strong>Terms And Conditions :</strong></p><p><br></p><p>•&nbsp;Tickets once booked cannot be exchanged or refunded.</p><p><br></p><p>• An Internet handling fee per ticket may be levied. Please check the total amount before payment.</p><p><br></p><p>• We recommend that you arrive at-least 30 minutes’ prior at the venue for a seamless entry.</p><p><br></p><p>• It is mandatory to wear masks at all times and follow social distancing norms.</p><p><br></p><p>• Please do not purchase tickets if you feel sick.</p><p><br></p><p>• Unlawful resale (or attempted unlawful resale) of a ticket would lead to seizure or cancellation of that ticket without refund or other compensation.</p><p><br></p><p>• Rights of admission reserved.</p><p><br></p><p>• These terms and conditions are subject to change from time to time at the discretion of the organizer.</p><p><br></p><p><strong>Ticket Price :</strong></p><p><strong>500 Onwards</strong></p><p><br></p><p><strong>Click Here To Book Your Ticket :</strong></p><p><a href=\"https://in.bookmyshow.com/events/50-years-of-rajinism/ET00414861/ticket?venueCode=KACT&amp;date=20241207&amp;time=1800\" rel=\"noopener noreferrer\" target=\"_blank\">https://in.bookmyshow.com/events/50-years-of-rajinism/ET00414861/ticket?venueCode=KACT&amp;date=20241207&amp;time=1800</a></p><p><br></p><p><br></p><p><br></p><p><br></p>",
        "priority": false,
        "from": "2024-12-07T12:30:00.000Z",
        "to": "2024-12-07T15:30:00.000Z",
        "place": "Corporation Kalai Arangam",
        "address": "Corporation Kalai Arangam,\nTV Swamy Road,\nR.S. Puram, \nCoimbatore.",
        "websites": "https://in.bookmyshow.com/events/50-years-of-rajinism/ET00414861",
        "email": null,
        "contacts": null,
        "area_1": "R.S. Puram",
        "area_2": null,
        "area_3": null,
        "city": "Coimbatore",
        "date": "16 Oct, 2024",
        "time": "8 - 10 PM",
        "state": null,
        "country": null,
        "zipcode": "641002",
        "priorities": null,
        "is_favourite": null,
        "on_reminder": null,
        "favourite_count": "0",
        "location": {
            "latitude": null,
            "longitude": null
        },
        "category": "Arts & Music",
        "poster": "https://cityquest-production.s3.ap-south-1.amazonaws.com/admin-assets/50.jpg"
    },
    {
        "id": 682,
        "title": "Faiyaaz Hussain Live",
        "status": "Published",
        "description": "<p>After his first video being a big hit, Faiyaaz is now touring with his solo comedy show, this show is addresses a lot of socio political issues around us. Come to the show if you want to talk, flirt or heckle.</p><p><br></p><p><strong>Terms And Conditions :</strong></p><p><br></p><p>• Tickets once booked cannot be exchanged or refunded.</p><p><br></p><p>• An Internet handling fee per ticket may be levied. Please check the total amount before payment.</p><p><br></p><p>• We recommend that you arrive at-least 30 minutes prior at the venue for a seamless entry .</p><p><br></p><p>• It is mandatory to wear masks at all times and follow social distancing norms.</p><p><br></p><p>• Please do not purchase tickets if you feel sick.</p><p><br></p><p>• Unlawful resale (or attempted unlawful resale) of a ticket would lead to seizure or cancellation of that ticket without refund or other compensation.</p><p><br></p><p>• Rights of admission reserved.</p><p><br></p><p>• These terms and conditions are subject to change from time to time at the discretion of the organizer.</p><p><br></p><p><strong>Ticket price :</strong></p><p><strong>349 Onwards</strong></p><p><br></p><p><strong>Click Here To Book Your Ticket :</strong></p><p><a href=\"https://in.bookmyshow.com/events/faiyaaz-hussain-live/ET00398371/booking-step/venue\" rel=\"noopener noreferrer\" target=\"_blank\">https://in.bookmyshow.com/events/faiyaaz-hussain-live/ET00398371/booking-step/venue</a></p>",
        "priority": false,
        "from": "2024-12-07T13:30:00.000Z",
        "to": "2024-12-07T14:55:00.000Z",
        "place": "Medai the stage Coimbatore",
        "address": "Medai the stage Coimbatore,\nKamarajar Road,\nNear Hope College, \nChitra Nagar, \nHope College, \nCoimbatore.",
        "websites": "https://in.bookmyshow.com/events/faiyaaz-hussain-live/ET00398371",
        "email": null,
        "contacts": null,
        "area_1": "Hope College",
        "area_2": null,
        "area_3": null,
        "city": "Coimbatore",
        "date": "22 Oct, 2024",
        "time": "01 - 06 PM",
        "state": null,
        "country": null,
        "zipcode": "641004",
        "priorities": null,
        "is_favourite": null,
        "on_reminder": null,
        "favourite_count": "0",
        "location": {
            "latitude": null,
            "longitude": null
        },
        "category": "Arts & Music",
        "poster": "https://cityquest-production.s3.ap-south-1.amazonaws.com/admin-assets/fhl.jpg"
    },
    {
        "id": 701,
        "title": "Human Library",
        "status": "Published",
        "description": "<p><br></p><p>Join us for an immersive and transformative event - the `Human Library`.</p><p><br></p><p>Here, `books` are real people with unique stories, ready to share their life experiences.</p><p><br></p><p>In this one-of-a-kind library, you `borrow` individuals for insightful conversations, engaging in deep dialogue that uncovers the layers of their life narratives.</p><p><br></p><p>This event is designed to promote understanding, challenge stereotypes, and celebrate the diversity of human experience.</p><p><br></p><p>Step into the shoes of others, gain new perspectives, and celebrate the art of storytelling.</p><p><br></p><p>Our Human Library is a safe space to ask, learn, and connect.</p><p><br></p><p>Get ready to turn a new page in your understanding of the world around you.</p><p><br></p><p><br></p><p><br></p><p><br></p><p><br></p><p><strong>Terms And Conditions :</strong></p><p><br></p><p>• Tickets once booked cannot be exchanged or refunded.</p><p><br></p><p>• An Internet handling fee per ticket may be levied. Please check the total amount before payment.</p><p><br></p><p>• We recommend that you arrive at-least 30 minutes prior at the venue for a seamless entry .</p><p><br></p><p>• It is mandatory to wear masks at all times and follow social distancing norms.</p><p><br></p><p>• Please do not purchase tickets if you feel sick.</p><p><br></p><p>• Unlawful resale (or attempted unlawful resale) of a ticket would lead to seizure or cancellation of that ticket without refund or other compensation.</p><p><br></p><p>• Rights of admission reserved.</p><p><br></p><p>• These terms and conditions are subject to change from time to time at the discretion of the organizer.</p><p><br></p><p><br></p><p><strong>Ticket price :</strong></p><p><strong>499 Onwards</strong></p><p><br></p><p><br></p><p><strong>Click here To Book Your Ticket :</strong></p><p><a href=\"https://in.bookmyshow.com/events/human-library/ET00361920/venue\" rel=\"noopener noreferrer\" target=\"_blank\">https://in.bookmyshow.com/events/human-library/ET00361920/venue</a></p>",
        "priority": false,
        "from": "2024-12-08T10:30:00.000Z",
        "to": "2024-12-08T11:30:00.000Z",
        "place": "Burger Ka Baap - BKB Cafe",
        "address": "Burger Ka Baap - BKB Cafe,\nSree Narayana Guru Road,\nBehind City Union Bank,\nNesavaalar Colony,\nSaibaba Colony, \nCoimbatore,\n",
        "websites": "https://in.bookmyshow.com/events/human-library/ET00361920",
        "email": null,
        "contacts": null,
        "area_1": "Saibaba Colony",
        "area_2": null,
        "area_3": null,
        "city": "Coimbatore",
        "date": "25 Oct, 2024",
        "time": "8 - 11 PM",
        "state": null,
        "country": null,
        "zipcode": "641011",
        "priorities": null,
        "is_favourite": null,
        "on_reminder": null,
        "favourite_count": "0",
        "location": {
            "latitude": null,
            "longitude": null
        },
        "category": "Others",
        "poster": "https://cityquest-production.s3.ap-south-1.amazonaws.com/admin-assets/human.jpg"
    }
];
export default eventImages;